function OMEGA = OMEGA_CALC(OMEGA,OMEGA_ip1,OMEGA_im1,OMEGA_jp1,OMEGA_jm1,U_ip1,U_im1,V_jp1,V_jm1,d2,djp1,djm1,dip1,dim1,alpha,alphaX,alphaY,dx,dy,dt)
% OMEGA = OMEGA.*(1-alpha./(d.^2)) + ...
%         OMEGA_ip1.*(-(dt/(2*dx)).*U_ip1.*dip1 + alphaX)./(d.^2) + ...
%         OMEGA_im1.*( (dt/(2*dx)).*U_im1.*dim1 + alphaX)./(d.^2) + ...
%         OMEGA_jp1.*(-(dt/(2*dy)).*V_jp1.*djp1 + alphaY)./(d.^2) + ...
%         OMEGA_jm1.*( (dt/(2*dy)).*V_jm1.*djm1 + alphaY)./(d.^2);

OMEGA =  OMEGA.*(1-alpha./(d2)) + ...
        (OMEGA_ip1.*(-(dt/(2*dx)).*U_ip1.*dip1 + alphaX) + ...
         OMEGA_im1.*( (dt/(2*dx)).*U_im1.*dim1 + alphaX) + ...
         OMEGA_jp1.*(-(dt/(2*dy)).*V_jp1.*djp1 + alphaY) + ...
         OMEGA_jm1.*( (dt/(2*dy)).*V_jm1.*djm1 + alphaY)) ./ d2;